name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
          pip install pyinstaller -i https://pypi.tuna.tsinghua.edu.cn/simple

      - name: Build EXE (onefile, windowed, with data)
        run: |
          pyinstaller --noconfirm --onefile --windowed --name joco ^
            --collect-submodules pandas ^
            --add-data "CPS团链产业777.xls;." ^
            main.py

      - name: Upload artifact (all dist outputs)
        uses: actions/upload-artifact@v4
        with:
          name: joco-windows-dist
          path: dist/

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-build-log
          path: build/

